version: '{build}'

branches:
  only:
    - master
    - /.*master.*/


image:
  - Ubuntu2004
  - Visual Studio 2019
  - macos-monterey

environment:
  matrix:
    - SHARED: True
    - SHARED: False

configuration:
  - Release

#platform:
#C:\  - x86

cache:
  - c:\.conan\ -> **\conanfile.py
  - c:\conan\ -> **\conanfile.py
  - /home/appveyor/.conan -> **/conanfile.py
  - /Users/appveyor/.conan -> **/conanfile.py

matrix:
  fast_finish: true
  
init:
  - cmd: |-
      echo %APPVEYOR_BUILD_WORKER_IMAGE%
      echo %MSBUILD_FLAGS%
      
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  

before_build:
  - cmd: |-
      set PATH=C:\Python39-x64\;C:\Python39-x64\Scripts;C:\Ruby30\bin;%PATH%
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
      if not exist C:\conan mkdir C:\conan
      if %SHARED%==True (set CONAN_PROFILE=conan/profiles/vs64shared) else (set CONAN_PROFILE=conan/profiles/vs64)
      set CONAN_USER_HOME=C:\conan
      set
      pip install --force-reinstall -v "conan==1.59.0"
      conan export conan/mqtt_cpp
      conan export conan/mruby
      conan install . -if build --build=missing -pr %CONAN_PROFILE% -o run_tests=False -o shared=%SHARED% -o with_docs=False
  - sh: |-
      export PATH=$HOME/venv3.10/bin:$PATH
      if [[ $APPVEYOR_BUILD_WORKER_IMAGE = "Ubuntu2004" ]]
      then
        sudo apt update
        sudo apt install -y build-essential cmake gcc-11 g++-11 python3 autoconf automake
        export CONAN_PROFILE=conan/profiles/gcc-appveyor
      elif [[ $APPVEYOR_BUILD_WORKER_IMAGE = "macOS-Monterey" ]]
      then
        export CONAN_PROFILE=conan/profiles/macos
      else
        echo "*NIX Operating System" $APPVEYOR_BUILD_WORKER_IMAGE " Not Supported"
        exit 99
      fi
      pip install --force-reinstall -v "conan==1.59.0"
      conan export conan/mqtt_cpp
      conan export conan/mruby
      conan install . -if build --build=missing -pr $CONAN_PROFILE -o run_tests=False -o shared=$SHARED -o with_docs=False

build:
  verbosity: minimal
  parallel: true

build_script:
  - conan build . -bf build

test_script:
  - cmd: |-
      cd %APPVEYOR_BUILD_FOLDER%/build
      ctest -C Release --output-on-failure
  - sh: |-
      cd ${APPVEYOR_BUILD_FOLDER}/build
      ctest --output-on-failure

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - conanfile.py
    - src/
    - test/
    - cmake/
    - agent/
    - agent_lib/
    - conan/

