services:
  agent:
    build:
      context: ../..
      dockerfile: docker/compose/agent/Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mazak
      - okuma
  mazak:
    build:
      context: ../..
      dockerfile: docker/compose/adapter/Dockerfile
      args:
        - LOG_FILE=mazak.txt
  okuma:
    build:
      context: ../..
      dockerfile: docker/compose/adapter/Dockerfile
      args:
        - LOG_FILE=okuma.txt

    
